name: CI

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Run tests
    steps:
      - name: Check out code from GitHub
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install homeassistant colorlog
      
      - name: Run hassfest to validate
        uses: home-assistant/actions/hassfest@master
      
      - name: Validate Python syntax
        run: |
          python -m py_compile custom_components/custom_component_monitor/*.py
      
      - name: Check code style with black
        run: |
          pip install black
          black --check --diff custom_components/
        continue-on-error: true
      
      - name: Check imports with isort
        run: |
          pip install isort
          isort --check-only --diff custom_components/
        continue-on-error: true