name: Release

on:
  release:
    types: [published]

jobs:
  release:
    name: Prepare release
    runs-on: ubuntu-latest
    steps:
      - name: Check out code from GitHub
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install homeassistant
      
      - name: Run hassfest to validate
        uses: home-assistant/actions/hassfest@master
      
      - name: Create zip file
        run: |
          cd custom_components/
          zip -r ../custom_component_monitor.zip custom_component_monitor/
      
      - name: Upload zip to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: custom_component_monitor.zip
          asset_name: custom_component_monitor.zip
          tag: ${{ github.ref }}
          overwrite: true